[versions]
agp = "8.13.2"
compose = "1.10.1"
dagger = "2.58"
lifecycle = "2.10.0"
room = "2.7.2"
protobuf = "4.33.4"
kotlin = "2.1.20"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"

# Compose
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-material3 = "androidx.compose.material3:material3:1.4.0"
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }

androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
material = "com.google.android.material:material:1.13.0"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.9.6"
androidx-activity-compose = "androidx.activity:activity-compose:1.12.2"
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

androidx-datastore = "androidx.datastore:datastore:1.2.0"

# Protobuf
protobuf-javalite = { group = "com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Dagger/Hilt
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"

timber = "com.jakewharton.timber:timber:5.0.1"

junit = "junit:junit:4.13.2"
androidx-test-junit = "androidx.test.ext:junit:1.3.0"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.7.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version = "2.1.20-1.0.32" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
protobuf = { id = "com.google.protobuf", version = "0.9.6" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version = "0.25.0" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
